<?php

declare(strict_types=1);

use JoeBocock\LaunchLibrary\Client\Client;
use JoeBocock\LaunchLibrary\Request\Agency\Index;

it('has values thay can be set', function () {
    $client = new Client(
        client: mockClient('tests/Fixture/Agency/Index.json')
    );

    $request = (new Index())
        ->setAbbrev('test')
        ->setAbbrevContains('test')
        ->setAdministrator('test')
        ->setAdministratorContains('test')
        ->setAgencyType(1)
        ->setAttemptedLandings(1)
        ->setAttemptedLandingsGT(1)
        ->setAttemptedLandingsGTE(1)
        ->setAttemptedLandingsLT(1)
        ->setAttemptedLandingsLTE(1)
        ->setConsecutiveSuccessfulLandings(1)
        ->setConsecutiveSuccessfulLandingsGT(1)
        ->setConsecutiveSuccessfulLandingsGTE(1)
        ->setConsecutiveSuccessfulLandingsLT(1)
        ->setConsecutiveSuccessfulLandingsLTE(1)
        ->setConsecutiveSuccessfulLaunches(1)
        ->setConsecutiveSuccessfulLaunchesGT(1)
        ->setConsecutiveSuccessfulLaunchesGTE(1)
        ->setConsecutiveSuccessfulLaunchesLT(1)
        ->setConsecutiveSuccessfulLaunchesLTE(1)
        ->setCountryCode(['example'])
        ->setDescription('test')
        ->setDescriptionContains('test')
        ->setFailedLandings(1)
        ->setFailedLandingsGT(1)
        ->setFailedLandingsGTE(1)
        ->setFailedLandingsLT(1)
        ->setFailedLandingsLTE(1)
        ->setFailedLaunches(1)
        ->setFailedLaunchesGT(1)
        ->setFailedLaunchesGTE(1)
        ->setFailedLaunchesLT(1)
        ->setFailedLaunchesLTE(1)
        ->setFeatured(true)
        ->setFoundingYear('test')
        ->setFoundingYearContains('test')
        ->setId(1)
        ->setIdGT(1)
        ->setIdGTE(1)
        ->setIdLT(1)
        ->setIdLTE(1)
        ->setName('test')
        ->setNameContains('test')
        ->setOrdering('test')
        ->setParent(1)
        ->setPendingLaunches(1)
        ->setPendingLaunchesGT(1)
        ->setPendingLaunchesGTE(1)
        ->setPendingLaunchesLT(1)
        ->setPendingLaunchesLTE(1)
        ->setSearch('test')
        ->setSpacecraft(true)
        ->setSuccessfulLandings(1)
        ->setSuccessfulLandingsGT(1)
        ->setSuccessfulLandingsGTE(1)
        ->setSuccessfulLandingsLT(1)
        ->setSuccessfulLandingsLTE(1)
        ->setSuccessfulLaunches(1)
        ->setSuccessfulLaunchesGT(1)
        ->setSuccessfulLaunchesGTE(1)
        ->setSuccessfulLaunchesLT(1)
        ->setSuccessfulLaunchesLTE(1)
        ->setTotalLaunchCount(1)
        ->setTotalLaunchCountGT(1)
        ->setTotalLaunchCountGTE(1)
        ->setTotalLaunchCountLT(1)
        ->setTotalLaunchCountLTE(1);

    expect(count($client->send($request)))->toBe(10);
});
